### ISSUE TITLE
MUMMER could not be found error

### ISSUE THREAD

**Issue by sams898** [jflucier/E2EAssembler#2]
Hello, 
I added in the path to the mummer dependency as described, but the program does not seem to be able to find it. It was installed with conda; does it need to be in a different location? Attached is a screenshot of my command and the error.

Thank you!
Samanth
<img width="872" alt="Screen Shot 2022-05-09 at 3 05 13 PM" src="https://user-images.githubusercontent.com/71793751/167480239-17f8cd8f-607f-45da-9e12-db200d859053.png">
a

**Comment by jflucier** [comment]
if you run in your shell:

```
nucmer -h

```

what is the output?

**Comment by sams898** [comment]
I get the program options:
USAGE: nucmer  [options]  <Reference>  <Query>

  DESCRIPTION:
    nucmer generates nucleotide alignments between two mutli-FASTA input
    files. The out.delta output file lists the distance between insertions
    and deletions that produce maximal scoring alignments between each
    sequence. The show-* utilities know how to read this format.

  MANDATORY:
    Reference       Set the input reference multi-FASTA filename
    Query           Set the input query multi-FASTA filename

  OPTIONS:
    --mum           Use anchor matches that are unique in both the reference
                    and query
    --mumcand       Same as --mumreference
    --mumreference  Use anchor matches that are unique in in the reference
                    but not necessarily unique in the query (default behavior)
    --maxmatch      Use all anchor matches regardless of their uniqueness

    -b|breaklen     Set the distance an alignment extension will attempt to
                    extend poor scoring regions before giving up (default 200)
    --[no]banded    Enforce absolute banding of dynamic programming matrix
                    based on diagdiff parameter EXPERIMENTAL (default no)
    -c|mincluster   Sets the minimum length of a cluster of matches (default 65)
    --[no]delta     Toggle the creation of the delta file (default --delta)
    --depend        Print the dependency information and exit
    -D|diagdiff     Set the maximum diagonal difference between two adjacent
                    anchors in a cluster (default 5)
    -d|diagfactor   Set the maximum diagonal difference between two adjacent
                    anchors in a cluster as a differential fraction of the gap
                    length (default 0.12)
    --[no]extend    Toggle the cluster extension step (default --extend)
    -f
    --forward       Use only the forward strand of the Query sequences
    -g|maxgap       Set the maximum gap between two adjacent matches in a
                    cluster (default 90)
    -h
    --help          Display help information and exit
    -l|minmatch     Set the minimum length of a single match (default 20)
    -o
    --coords        Automatically generate the original NUCmer1.1 coords
                    output file using the 'show-coords' program
    --[no]optimize  Toggle alignment score optimization, i.e. if an alignment
                    extension reaches the end of a sequence, it will backtrack
                    to optimize the alignment score instead of terminating the
                    alignment at the end of the sequence (default --optimize)
    -p|prefix       Set the prefix of the output files (default "out")
    -r
    --reverse       Use only the reverse complement of the Query sequences
    --[no]simplify  Simplify alignments by removing shadowed clusters. Turn
                    this option off if aligning a sequence to itself to look
                    for repeats (default --simplify)
    -V
    --version       Display the version information and exit

**Comment by jflucier** [comment]
please run these commands:

```
# go to e2eassembler path
git pull origin master

if ! command -v "nucmer" &> /dev/null
then
    echo "##**** MUMMER could not be found ****"
    echo "## Please install MUMMER and put in PATH"
    echo "## export PATH=/path/to/mummer:\$PATH"
    echo "##**********************************"
    echo "##"
else
    echo "mummer installed"
fi

echo $PATH
```

tks

**Comment by sams898** [comment]
Thank you! It looked like I was missing a part of the path and it went past that error now. Sorry another question; I have to have Python 2.7 in my path? I created a conda environment with Python 2.7.15 (as all of the base servers I use are python 3), but it still giving me an error now that "**** Python 2.7 could not be found ****". I performed the above test and saw that it is installed and that I was using the correct outputted path (/home/samsholes/anaconda3/envs/python2/bin/python2.7). I didn't see a python path in your sample configuration file but should I add it in? Thank you!

**Comment by jflucier** [comment]
tks for reporting bug. 

I applied a correction as python 2.7 is not required by version of software using these modules:

```
bash ${E2EAssembler}/01_split_by_coverage.sh my.example.config
bash ${E2EAssembler}/03_merge_assemblies.sh my.example.config
bash ${E2EAssembler}/04_annotate_asembly.sh my.example.config
bash ${E2EAssembler}/05_reads_telomere_length_distribution.split.sh my.example.config
bash ${E2EAssembler}/99_generate_hub_files.sh my.example.config

```

just do a git pull origin master in your E2EAssembler path and it should work.
