### ISSUE TITLE
Python 2.7 dependency

### ISSUE THREAD

**Issue by sams898** [jflucier/E2EAssembler#3]
Hello,

I apologize, I am still receiving the python 2.7 dependency error after pulling the updated master branch. Is there something else I should try? Thank you! Here is a photo
<img width="796" alt="Screen Shot 2022-05-10 at 9 25 20 AM" src="https://user-images.githubusercontent.com/71793751/167639135-43747470-8704-4c97-a3c7-5954d7839d32.png">
:

**Comment by jflucier** [comment]
sorry my bad... 

please git pull E2EAssembler again, it should work now

fixed with this [commit](https://github.com/jflucier/E2EAssembler/commit/a4d4c837faf037c6b1a94c07cc694d94588ff725)

**Comment by sams898** [comment]
Great, thank you! It is running
