### ISSUE TITLE
canu assembly cp -R

### ISSUE THREAD

**Issue by sams898** [jflucier/E2EAssembler#4]
Hello,
I am attempting to execute the canu assembly with the outputted command after examining the coverage and splitting the fastq files (bash /mithril/Data/Analysis/sam/220419_wt1b1wt2b2/canu_assembly/02_exec_canu.slurm.sh). I am working on a NAS server; when I used this command it appeared to cp -R the whole NAS directory? Is this supposed to happen; should I run the assembler elsewhere instead?
Thank you!

**Comment by jflucier** [comment]
what is your task scheduler on your NAS server (slurm, torq)?

The script is optimised to work on the localscratch directory of compute nodes. 

If you dont have a task scheduler on your server, the 01_split_by_coverage.sh also output a script 02_exec_canu.sh that can be runned locally. Just make sure you defined LOCAL_THREAD' and LOCAL_MEMORY properly in your config file.

Essentially the local execution iterates over you script fastq files to run canu

```
mkdir -p '$CANU_OUTPATH'
for f in '${NANOPORE_BASE}'.*.fastq
do
    __fastq_file=$(basename $f)
    __fastq_group=${__fastq_file%.fastq}
    mkdir -p '$CANU_OUTPATH'/${__fastq_group}
    rm -fr  '$CANU_OUTPATH'/${__fastq_group}/*
    echo "running assembly on $f"
    echo "ouptutting resulting assembly in '$PWD'/canu_assembly/${__fastq_group}"
    '$CANU' useGrid=false \
    -p ${__fastq_group} -d '$CANU_OUTPATH'/${__fastq_group} \
    genomeSize='$CANU_GENOME_SIZE'm maxThreads='$LOCAL_THREAD' maxMemory='$LOCAL_MEMORY' \
    -nanopore $f
    echo "done assembly of $f"
done

```

if you wish to run concurrently all assembly locally, just append a '&' to this line:
```

  '$CANU' useGrid=false \
    -p ${__fastq_group} -d '$CANU_OUTPATH'/${__fastq_group} \
    genomeSize='$CANU_GENOME_SIZE'm maxThreads='$LOCAL_THREAD' maxMemory='$LOCAL_MEMORY' \
    -nanopore $f &
```

WARNING: if you do this, do not forget to set thread and memory accordingly based on all fastq being analysed at the same time.

Please tell me if this works.

**Comment by sams898** [comment]
Thank you! There isn't a task scheduler so I am running it locally and used the 02_exec_canu.sh script this time. With this script, I am getting the error:

ERROR:  Invalid command line option '-nanopore'.  Did you forget quotes around options with spaces?
ERROR:  File supplied on command line; use -s, -pacbio-raw, -pacbio-corrected, -nanopore-raw, or -nanopore-corrected.
ERROR:  Invalid 'corErrorRate' specified; must be set

Attached is a full screenshot of the output. Should I set these parameters anywhere? Thanks!
<img width="768" alt="Screen Shot 2022-05-20 at 10 35 31 AM" src="https://user-images.githubusercontent.com/71793751/169551563-2489527d-1d4d-4a74-8164-c1f103f854d6.png">

**Comment by jflucier** [comment]
Sorry for delay. 

can you attach your 02_exec_canu.sh script so I can debug more easily.

Thank you

**Comment by jflucier** [comment]
I think the error is linked to the version of canu installed on your server. I tested using latest version 2.2 and option nanopore is specified by adding option 

```
$ /storage/app/canu/build/bin/canu

usage:   canu [-version] [-citation] \
              [-haplotype | -correct | -trim | -assemble | -trim-assemble] \
              [-s <assembly-specifications-file>] \
               -p <assembly-prefix> \
               -d <assembly-directory> \
               genomeSize=<number>[g|m|k] \
              [other-options] \
              [-haplotype{NAME} illumina.fastq.gz] \
              [-corrected] \
              [-trimmed] \
              [-pacbio |
               -nanopore |
               -pacbio-hifi] file1 file2 ...


```

Please install latest version of canu. To install canu, just follow these instructions:

```
curl -L https://github.com/marbl/canu/releases/download/v2.2/canu-2.2.tar.xz --output canu-2.2.tar.xz
tar -xJf canu-2.2.tar.xz
cd canu-2.2/src
make -j 8
cd ..

```

**Comment by sams898** [comment]
It is running now, thank you!
